import { gql } from 'apollo-server-express'

export default gql`
  extend type Query {
    stores(
      page: Int
      search: String
      limit: Int
      sort: String
      vendor: ID
    ): storeRes
    syncStores: Boolean
    store: Store @auth
    storeOne(id: ID, slug: String, domain: String): Store
  }

  extend type Mutation {
    saveStore(
      id: String!
      active: Boolean
      featured: Boolean
      adminNotifications: AdminNotificationIp
      address: String
      alert: String
      analyticsTrackingId: String
      banners: [String]
      city: String
      closed: Boolean
      closedMessage: String
      country: String
      currency: String
      currencyCode: String
      currencyDecimals: Float
      currencySymbol: String
      customerOrderNotifications: UserNotificationIp
      description: String
      detailMeta: String
      dimentionUnit: String
      domain: String
      email: String
      facebook: String
      facebookPixelId: String
      facebookUrl: String
      favicon: String
      firstName: String
      freeShippingOn: Float
      gdprCookieConsent: String
      google: String
      googleAdsTag: String
      homeMeta1: String
      homeMeta2: String
      homeMeta3: String
      homeMeta4: String
      img: String
      images: [String]
      bankAccountNo: String
      bankAccountHolderName: String
      bankIfscCode: String
      instagram: String
      instagramUrl: String
      isHideNilStock: Boolean
      isMegamenu: Boolean
      isOpen: Boolean
      isSearch: Boolean
      keywords: String
      lastName: String
      lat: Float
      legalName: String
      linkedin: String
      lng: Float
      locality: String
      logo: String
      logoDark: String
      logoMobile: String
      logoMobileDark: String
      minimumOrderValue: Float
      minOrderValue: Float
      name: String
      openGraphImage: String
      pageSize: Int
      phone: String
      pinterestTag: String
      pinterestUrl: String
      qrCode: String
      review: ReviewSettingIp
      searchbarText: String
      shipping: ShippingIp
      shippingCharge: Float
      shopAddress: String
      shopPhone: String
      slug: String
      refreshSlug: Boolean
      snapChatPixel: String
      state: String
      storeId: String
      timeZone: String
      timing: String
      title: String
      twitter: String
      twitterUrl: String
      websiteEmail: String
      websiteLegalName: String
      websiteName: String
      weightUnit: String
      youtubeUrl: String
      zip: Float
    ): OneStore @auth
    deleteStore(id: ID!): Boolean @admin
    populateDemoDataInStore(storeId: ID): Boolean @admin
    removeDemoDataInStore(storeId: ID): Boolean @admin
  }

  type Store {
    id: ID!
    active: Boolean
    featured: Boolean
    adminNotifications: AdminNotification
    address: String
    alert: String
    analyticsTrackingId: String
    banners: [String]
    city: String
    closed: Boolean
    closedMessage: String
    country: String
    currency: String
    currencyCode: String
    currencyDecimals: Float
    currencySymbol: String
    customerOrderNotifications: UserNotification
    description: String
    detailMeta: String
    dimentionUnit: String
    domain: String
    email: String
    facebook: String
    facebookPixelId: String
    facebookUrl: String
    favicon: String
    firstName: String
    freeShippingOn: Float
    gdprCookieConsent: String
    google: String
    googleAdsTag: String
    homeMeta1: String
    homeMeta2: String
    homeMeta3: String
    homeMeta4: String
    img: String
    images: [String]
    bankAccountNo: String
    bankAccountHolderName: String
    bankIfscCode: String
    instagram: String
    instagramUrl: String
    isHideNilStock: Boolean
    isMegamenu: Boolean
    isOpen: Boolean
    isSearch: Boolean
    keywords: String
    lastName: String
    lat: Float
    legalName: String
    linkedin: String
    lng: Float
    locality: String
    logo: String
    logoDark: String
    logoMobile: String
    logoMobileDark: String
    minimumOrderValue: Float
    minOrderValue: Float
    name: String
    openGraphImage: String
    pageSize: Int
    phone: String
    pinterestTag: String
    pinterestUrl: String
    qrCode: String
    review: ReviewSetting
    searchbarText: String
    shipping: Shipping
    shippingCharge: Float
    shopAddress: String
    shopPhone: String
    slug: String
    snapChatPixel: String
    state: String
    storeId: String
    timeZone: String
    timing: String
    title: String
    twitter: String
    twitterUrl: String
    user: User
    websiteEmail: String
    websiteLegalName: String
    websiteName: String
    weightUnit: String
    youtubeUrl: String
    zip: Float
    createdAt: String
    updatedAt: String
  }

  type OneStore {
    id: ID!
    active: Boolean
    featured: Boolean
    adminNotifications: AdminNotification
    address: String
    alert: String
    analyticsTrackingId: String
    banners: [String]
    city: String
    closed: Boolean
    closedMessage: String
    country: String
    currency: String
    currencyCode: String
    currencyDecimals: Float
    currencySymbol: String
    customerOrderNotifications: UserNotification
    description: String
    detailMeta: String
    dimentionUnit: String
    domain: String
    email: String
    facebook: String
    facebookPixelId: String
    facebookUrl: String
    favicon: String
    firstName: String
    freeShippingOn: Float
    gdprCookieConsent: String
    google: String
    googleAdsTag: String
    homeMeta1: String
    homeMeta2: String
    homeMeta3: String
    homeMeta4: String
    img: String
    images: [String]
    bankAccountNo: String
    bankAccountHolderName: String
    bankIfscCode: String
    instagram: String
    instagramUrl: String
    isHideNilStock: Boolean
    isMegamenu: Boolean
    isOpen: Boolean
    isSearch: Boolean
    keywords: String
    lastName: String
    lat: Float
    legalName: String
    linkedin: String
    lng: Float
    locality: String
    logo: String
    logoDark: String
    logoMobile: String
    logoMobileDark: String
    minimumOrderValue: Float
    minOrderValue: Float
    name: String
    openGraphImage: String
    pageSize: Int
    phone: String
    pinterestTag: String
    pinterestUrl: String
    qrCode: String
    review: ReviewSetting
    searchbarText: String
    shipping: Shipping
    shippingCharge: Float
    shopAddress: String
    shopPhone: String
    slug: String
    snapChatPixel: String
    state: String
    storeId: String
    timeZone: String
    timing: String
    title: String
    twitter: String
    twitterUrl: String
    user: ID
    websiteEmail: String
    websiteLegalName: String
    websiteName: String
    weightUnit: String
    youtubeUrl: String
    zip: Float
    createdAt: String
    updatedAt: String
  }

  type storeRes {
    data: [Store]
    count: Int
    pageSize: Int
    page: Int
  }
`
