export const {
  ORVILLE_URL = 'LULU_URL',
  ORVILLE_DOMAIN = 'LULU_DOMAIN',
  ORVILLE_CLIENT_ID = 'LULU_CLIENT_ID',
  ORVILLE_CLIENT_SECRET = 'LULU_CLIENT_SECRET',
  ORVILLE_ADMIN_USERNAME = 'LULU_USERNAME',
  ORVILLE_ADMIN_PASSWORD = 'LULU_PASSWORD',
} = process.env
