export default [
  {
    _id: '5c596becfe3afe5344187129',
    name: 'Breakfast & Dairy',
    description:
      'Breakfast & Dairy Best Offers, Milk & Milk Products, Bread & Eggs, Paneer & Curd, Butter & Cheese, Breakfast Cereal & Mixes, Jams, Honey & Spreads',
    img: '/images/category/NjVoKWQfl-breakfast-dairy.webp',
    link: 'https://grofers.com/cn/breakfast-dairy/cid/14',
    active: true,
    level: 0,
    position: 7,
    index: 1,
    featured: true,
    children: [],
    namePath: ' / Breakfast & Dairy',
    path: '/5c596becfe3afe5344187129',
    pathA: [],
    q: 'breakfast & dairy true',
    slug: 'breakfast-dairy',
    slugPath: ' / breakfast-dairy',
    megamenu: true,
    user: '5ea3fa5b880b0b23119f4c14',
    shopbycategory: false,
  },
  {
    _id: '5c596becfe3afe534418712b',
    name: 'Pet Care',
    description: 'Dog Supplies, Cat Supplies',
    img: '/images/category/qrwowLkFR-petcare.webp',
    link: 'https://grofers.com/cn/pet-care/cid/5',
    active: true,
    level: 0,
    position: 11,
    index: 1,
    featured: true,
    children: [],
    namePath: ' / Pet Care',
    path: '/5c596becfe3afe534418712b',
    pathA: [],
    q: 'pet care true',
    slug: 'pet-care',
    slugPath: ' / pet-care',
    megamenu: true,
    user: '5ea3fa5b880b0b23119f4c14',
    shopbycategory: false,
  },
  {
    _id: '5c596becfe3afe5344187127',
    name: 'Baby & Kids',
    description:
      'Baby Food, Diapers & Wipes, Baby Skin & Hair Care, Baby Accessories & More, Kids Furnishing, Toys & More',
    img: '/images/category/q77S4BKVv-baby-kids.webp',
    link: 'https://grofers.com/cn/baby-kids/cid/7',
    active: true,
    level: 0,
    position: 10,
    index: 1,
    featured: true,
    children: [],
    namePath: ' / Baby & Kids',
    path: '/5c596becfe3afe5344187127',
    pathA: [],
    q: 'baby & kids true',
    slug: 'baby-kids',
    slugPath: ' / baby-kids',
    megamenu: true,
    user: '5ea3fa5b880b0b23119f4c14',
    shopbycategory: false,
  },
  {
    _id: '5c596becfe3afe5344187126',
    name: 'Household Needs',
    description:
      'Household Best Offers, Laundry Detergents, Dishwashers, Cleaners, Cleaning Tools & Brushes, Pooja Needs, Repellents, Home & Car Fresheners, Tissues & Disposables, Premium Home Care, Shoe Care',
    img: '/images/category/K6oj-qjPr-household-needs.webp',
    link: 'https://grofers.com/cn/household-needs/cid/18',
    active: true,
    level: 0,
    position: 3,
    index: 1,
    featured: true,
    children: [],
    namePath: ' / Household Needs',
    path: '/5c596becfe3afe5344187126',
    pathA: [],
    q: 'household needs true',
    slug: 'household-needs',
    slugPath: ' / household-needs',
    megamenu: true,
    user: '5ea3fa5b880b0b23119f4c14',
    shopbycategory: false,
  },
  {
    _id: '5c596becfe3afe5344187125',
    name: 'Vegetables & Fruits',
    description: 'Fruits, Potato - Onion - Tomato',
    img: null,
    link: 'https://grofers.com/cn/vegetables-fruits/cid/1487',
    active: true,
    level: 1,
    position: 1,
    index: 1,
    featured: true,
    children: [],
    namePath: ' / Vegetables & Fruits',
    path: '/5c596becfe3afe5344187125',
    pathA: [],
    q: 'vegetables & fruits true',
    slug: 'vegetables-fruits',
    slugPath: ' / vegetables-fruits',
    megamenu: true,
    user: '5ee1112bd82eb1522c360251',
    shopbycategory: false,
  },
  {
    _id: '5c596becfe3afe5344187123',
    name: 'Home & Kitchen',
    description:
      'Best Deals & Offers, Cookware, Storage & Containers, Kitchen Tools & Accessories, Dining & Serving, Bags & Travel Accessories, Bathroom Essentials, Cleaning Equipment, Electrical Goods & Accessories, Tools, Auto & Sports, Stationery & Magazines, Gas Stoves',
    img: '/images/category/IogtedO0L-home-kitchen.webp',
    link: 'https://grofers.com/cn/home-kitchen/cid/1047',
    active: true,
    level: 0,
    position: 4,
    index: 1,
    featured: true,
    children: [],
    namePath: ' / Home & Kitchen',
    path: '/5c596becfe3afe5344187123',
    pathA: [],
    q: 'home & kitchen true',
    slug: 'home-kitchen',
    slugPath: ' / home-kitchen',
    megamenu: true,
    user: '5ea3fa5b880b0b23119f4c14',
    shopbycategory: false,
  },
  {
    _id: '5c596becfe3afe5344187121',
    name: 'Beverages',
    description:
      'Beverages Best Offers, Soft Drinks, Juices & Concentrates, Tea & Coffee, Health & Energy Drinks, Water & Soda, Milk Drinks',
    img: '/images/category/pn1CTvY0y-beverages.webp',
    link: 'https://grofers.com/cn/beverages/cid/12',
    active: true,
    level: 0,
    position: 6,
    index: 1,
    featured: true,
    children: [],
    namePath: ' / Beverages',
    path: '/5c596becfe3afe5344187121',
    pathA: [],
    q: 'beverages true',
    slug: 'beverages',
    slugPath: ' / beverages',
    megamenu: true,
    user: '5ea3fa5b880b0b23119f4c14',
    shopbycategory: false,
  },
  {
    _id: '5c596becfe3afe5344187120',
    name: 'Personal Care',
    description:
      'Personal Care Best Offers, Bath & Body, Hair Care, Skin Care, Oral Care, Deos & Perfumes, Face Care, Feminine Hygiene, Shaving Needs, Health & Wellness, Cosmetics',
    img: '/images/category/87Bc8CUr3-personal-care.webp',
    link: 'https://grofers.com/cn/personal-care/cid/163',
    active: true,
    level: 0,
    position: 2,
    index: 1,
    featured: true,
    children: [],
    namePath: ' / Personal Care',
    path: '/5c596becfe3afe5344187120',
    pathA: [],
    q: 'personal care true',
    slug: 'personal-care',
    slugPath: ' / personal-care',
    megamenu: true,
    user: '5ea3fa5b880b0b23119f4c14',
    shopbycategory: false,
  },
  {
    _id: '5c596becfe3afe534418711f',
    name: 'Grocery & Staples',
    description:
      'Pulses, Atta & Other Flours, Rice & Other Grains, Dry Fruits & Nuts, Edible Oils, Ghee & Vanaspati, Spices, Salt & Sugar, Organic Staples, Potato - Onion - Tomato, Fruits',
    img: '/images/category/9YwIIBoMB-grocery-staples.webp',
    link: 'https://grofers.com/cn/grocery-staples/cid/16',
    active: true,
    level: 0,
    position: 1,
    index: 1,
    featured: true,
    children: [],
    namePath: ' / Grocery & Staples',
    path: '/5c596becfe3afe534418711f',
    pathA: [],
    q: 'grocery & staples true',
    slug: 'grocery-staples',
    slugPath: ' / grocery-staples',
    megamenu: true,
    user: '5ea3fa5b880b0b23119f4c14',
    shopbycategory: false,
  },
]
