export default [
  {
    _id: '5ecffda99e8b394b6f8967ad',
    vendor: '5ed14bbe9e8b394b6f8967cf',
    badge: {
      recommended: false,
      hot: false,
      sale: false,
      new: false,
      featured: false,
    },
    categories: [],
    city: 'Mumbai',
    active: true,
    approved: false,
    position: 0,
    popularity: null,
    sales: 0,
    name: 'Diaper',
    price: null,
    stock: null,
    img: '/images/product/8S__28aYm-author.jpg',
    category: '5c596becfe3afe5344187127',
    slug: 'diaper',
    q: 'diaper',
  },

  {
    _id: '5c598f5bfe3afe40045602ce',
    vendor: '5ed14bbe9e8b394b6f8967cf',
    name: 'Tomato - Hybrid',
    size: '1  kg',
    mrp: '46',
    price: 35,
    img: '/images/product/vegetables-fruits/tomato-hybrid.webp',
    slug: 'tomato-hybrid',
    active: true,
    approved: true,
    position: 0,
    brandName: 'Tomato',
    variants: [
      {
        _id: '5c598c89a64e12624c96faf2',
        size: '1  kg',
        stock: 1000,
        price: '35',
        mrp: '46',
        img: [
          {
            small: '/images/product/vegetables-fruits/tomato-hybrid.webp',
          },
        ],
      },
    ],
    popularity: 0,
    badge: {
      recommended: false,
      hot: false,
      sale: false,
      new: false,
      featured: false,
    },
    category_name: 'vegetables-fruits',
    city: 'Mumbai',
    stock: 100,
    img_featured: '/images/product/vegetables-fruits/tomato-hybrid.webp',
    category: '5c596becfe3afe5344187125',
    description: null,
    keywords: null,
    metaDescription: null,
    title: null,
    categories: [],
    q: 'tomato - hybrid',
    sales: 0,
  },

  {
    _id: '5c598f5bfe3afe40045602cc',
    vendor: '5ed14bbe9e8b394b6f8967cf',
    name: 'Pomegranate (Anaar)',
    size: '4 units (0.9-1.2 kg)',
    mrp: '150',
    price: '115',
    img: '/images/product/vegetables-fruits/pomegranate-anaar.webp',
    slug: 'pomegranate-anaar',
    active: true,
    approved: true,
    position: 0,
    brandName: 'Pomegranate',
    variants: [
      {
        _id: '5c598c89a64e12624c96faf0',
        size: '4 units (0.9-1.2 kg)',
        stock: 1000,
        price: '115',
        mrp: '150',
        img: [
          {
            small: '/images/product/vegetables-fruits/pomegranate-anaar.webp',
          },
        ],
      },
    ],
    popularity: 0,
    badge: {
      featured: false,
    },
    category_name: 'vegetables-fruits',
    city: 'Mumbai',
    stock: 100,
    img_featured: '/images/product/vegetables-fruits/pomegranate-anaar.webp',
    category: '5c596becfe3afe5344187125',
  },

  {
    _id: '5c598f5bfe3afe40045602cb',
    vendor: '5ed14bbe9e8b394b6f8967cf',
    name: 'Onion',
    size: '1  kg',
    mrp: '24',
    price: '18',
    img: '/images/product/vegetables-fruits/onion.webp',
    slug: 'onion',
    active: true,
    approved: true,
    position: 0,
    brandName: 'Onion',
    variants: [
      {
        _id: '5c598c89a64e12624c96faef',
        size: '1  kg',
        stock: 1000,
        price: '18',
        mrp: '24',
        img: [
          {
            small: '/images/product/vegetables-fruits/onion.webp',
          },
        ],
      },
    ],
    popularity: 0,
    badge: {
      featured: false,
    },
    category_name: 'vegetables-fruits',
    city: 'Mumbai',
    stock: 100,
    img_featured: '/images/product/vegetables-fruits/onion.webp',
    category: '5c596becfe3afe5344187125',
  },

  {
    _id: '5c598f5bfe3afe40045602ca',
    vendor: '5ed14bbe9e8b394b6f8967cf',
    name: 'Kinnow',
    size: '1 kg',
    mrp: '47',
    price: '36',
    img: '/images/product/vegetables-fruits/kinnow.webp',
    slug: 'kinnow',
    active: true,
    approved: true,
    position: 0,
    brandName: 'Kinnow',
    variants: [
      {
        _id: '5c598c89a64e12624c96faee',
        size: '1 kg',
        stock: 1000,
        price: '36',
        mrp: '47',
        img: [
          {
            small: '/images/product/vegetables-fruits/kinnow.webp',
          },
        ],
      },
    ],
    popularity: 0,
    badge: {
      featured: false,
    },
    category_name: 'vegetables-fruits',
    city: 'Mumbai',
    stock: 100,
    img_featured: '/images/product/vegetables-fruits/kinnow.webp',
    category: '5c596becfe3afe5344187125',
  },

  {
    _id: '5c598f5bfe3afe40045602c9',
    vendor: '5ed14bbe9e8b394b6f8967cf',
    name: 'Washington Apple',
    size: '4 units (600-800 g)',
    mrp: '202',
    price: '155',
    img: '/images/product/vegetables-fruits/washington-apple.webp',
    slug: 'washington-apple',
    active: true,
    approved: true,
    position: 0,
    brandName: 'Washington',
    variants: [
      {
        _id: '5c598c89a64e12624c96faed',
        size: '4 units (600-800 g)',
        stock: 1000,
        price: '155',
        mrp: '202',
        img: [
          {
            small: '/images/product/vegetables-fruits/washington-apple.webp',
          },
        ],
      },
    ],
    popularity: 0,
    badge: {
      featured: false,
    },
    category_name: 'vegetables-fruits',
    city: 'Mumbai',
    stock: 100,
    img_featured: '/images/product/vegetables-fruits/washington-apple.webp',
    category: '5c596becfe3afe5344187125',
  },

  {
    _id: '5c598f5bfe3afe40045602c8',
    vendor: '5ed14bbe9e8b394b6f8967cf',
    name: 'Kinnaur Apple',
    size: '6 units',
    mrp: '207',
    price: '159',
    img: '/images/product/vegetables-fruits/kinnaur-apple.webp',
    slug: 'kinnaur-apple',
    active: true,
    approved: true,
    position: 0,
    brandName: 'Kinnaur',
    variants: [
      {
        _id: '5c598c89a64e12624c96faec',
        size: '6 units',
        stock: 1000,
        price: '159',
        mrp: '207',
        img: [
          {
            small: '/images/product/vegetables-fruits/kinnaur-apple.webp',
          },
        ],
      },
    ],
    popularity: 0,
    badge: {
      featured: false,
    },
    category_name: 'vegetables-fruits',
    city: 'Mumbai',
    stock: 100,
    img_featured: '/images/product/vegetables-fruits/kinnaur-apple.webp',
    category: '5c596becfe3afe5344187125',
  },

  {
    _id: '5c598f5bfe3afe40045602c7',
    vendor: '5ed14bbe9e8b394b6f8967cf',
    name: 'Green Apple - Imported',
    size: '4 units',
    mrp: '208',
    price: '160',
    img: '/images/product/vegetables-fruits/green-apple-imported.webp',
    slug: 'green-apple-imported',
    active: true,
    approved: true,
    position: 0,
    brandName: 'Green',
    variants: [
      {
        _id: '5c598c89a64e12624c96faeb',
        size: '4 units',
        stock: 1000,
        price: '160',
        mrp: '208',
        img: [
          {
            small:
              '/images/product/vegetables-fruits/green-apple-imported.webp',
          },
        ],
      },
    ],
    popularity: 0,
    badge: {
      featured: false,
    },
    category_name: 'vegetables-fruits',
    city: 'Mumbai',
    stock: 100,
    img_featured: '/images/product/vegetables-fruits/green-apple-imported.webp',
    category: '5c596becfe3afe5344187125',
  },

  {
    _id: '5c598f5bfe3afe40045602c6',
    vendor: '5ed14bbe9e8b394b6f8967cf',
    name: 'Kiwi',
    size: '3 units',
    mrp: '90',
    price: '69',
    img: '/images/product/vegetables-fruits/kiwi.webp',
    slug: 'kiwi',
    active: true,
    approved: true,
    position: 0,
    brandName: 'Kiwi',
    variants: [
      {
        _id: '5c598c89a64e12624c96faea',
        size: '3 units',
        stock: 1000,
        price: '69',
        mrp: '90',
        img: [
          {
            small: '/images/product/vegetables-fruits/kiwi.webp',
          },
        ],
      },
    ],
    popularity: 0,
    badge: {
      featured: false,
    },
    category_name: 'vegetables-fruits',
    city: 'Mumbai',
    stock: 100,
    img_featured: '/images/product/vegetables-fruits/kiwi.webp',
    category: '5c596becfe3afe5344187125',
  },

  {
    _id: '5c598f5bfe3afe40045602c5',
    vendor: '5ed14bbe9e8b394b6f8967cf',
    name: 'Sweet Tamarind (Imli) - Box',
    size: '250 gm',
    mrp: '140',
    price: '99',
    img: '/images/product/vegetables-fruits/sweet-tamarind-imli-box.webp',
    slug: 'sweet-tamarind-imli-box',
    active: true,
    approved: true,
    position: 0,
    brandName: 'Sweet',
    variants: [
      {
        _id: '5c598c89a64e12624c96fae9',
        size: '250 gm',
        stock: 1000,
        price: '99',
        mrp: '140',
        img: [
          {
            small:
              '/images/product/vegetables-fruits/sweet-tamarind-imli-box.webp',
          },
        ],
      },
    ],
    popularity: 0,
    badge: {
      featured: false,
    },
    category_name: 'vegetables-fruits',
    city: 'Mumbai',
    stock: 100,
    img_featured:
      '/images/product/vegetables-fruits/sweet-tamarind-imli-box.webp',
    category: '5c596becfe3afe5344187125',
  },

  {
    _id: '5c598f5bfe3afe40045602c4',
    vendor: '5ed14bbe9e8b394b6f8967cf',
    name: 'Pineapple',
    size: '1 unit  (1-1.4 kg)',
    mrp: '77',
    price: '59',
    img: '/images/product/vegetables-fruits/pineapple.webp',
    slug: 'pineapple',
    active: true,
    approved: true,
    position: 0,
    brandName: 'Pineapple',
    variants: [
      {
        _id: '5c598c89a64e12624c96fae8',
        size: '1 unit  (1-1.4 kg)',
        stock: 1000,
        price: '59',
        mrp: '77',
        img: [
          {
            small: '/images/product/vegetables-fruits/pineapple.webp',
          },
        ],
      },
    ],
    popularity: 0,
    badge: {
      featured: false,
    },
    category_name: 'vegetables-fruits',
    city: 'Mumbai',
    stock: 100,
    img_featured: '/images/product/vegetables-fruits/pineapple.webp',
    category: '5c596becfe3afe5344187125',
  },

  {
    _id: '5c598f5bfe3afe40045602c3',
    vendor: '5ed14bbe9e8b394b6f8967cf',
    name: 'Brown Coconut',
    size: '1 unit',
    mrp: '51',
    price: '39',
    img: '/images/product/vegetables-fruits/brown-coconut.webp',
    slug: 'brown-coconut',
    active: true,
    approved: true,
    position: 0,
    brandName: 'Brown',
    variants: [
      {
        _id: '5c598c89a64e12624c96fae7',
        size: '1 unit',
        stock: 1000,
        price: '39',
        mrp: '51',
        img: [
          {
            small: '/images/product/vegetables-fruits/brown-coconut.webp',
          },
        ],
      },
    ],
    popularity: 0,
    badge: {
      featured: false,
    },
    category_name: 'vegetables-fruits',
    city: 'Mumbai',
    stock: 100,
    img_featured: '/images/product/vegetables-fruits/brown-coconut.webp',
    category: '5c596becfe3afe5344187125',
  },
]
