export default {
  title: 'Litekart ecommerce',
  alert: 'We experiencing an incident and we are on it.',
  keywords: 'Litekart, ecommerce, multi vendor',
  description: 'Litekart ecommerce home page description',
  googleMapsApi: '',
  RAZORPAY_KEY_ID: '',
  closed: false,
  closedMessage: '',
  currencyCode: 'INR',
  currencySymbol: '₹',
  enableTax: false,
  facebook: '',
  favicon: '',
  google: '',
  instagram: '',
  logo: '',
  logoDark: '',
  logoMobile: '',
  logoMobileDark: '',
  openGraphImage: '',
  pageSize: 40,
  product: {
    moderate: false,
  },
  shipping: {
    deliveryDays: '',
    charge: 120,
    free: '',
    method: '',
  },
  shopAddress: '',
  shopEmail: '',
  shopPhone: '',
  stripePublishableKey: '',
  twitter: '',
  websiteName: 'Litekart',
  websiteLegalName: 'Litekart',
  otpLogin: true,
  searchbarText: 'Search for products, brands and more',
  demo: false,
  storage: {
    provider: 'azure',
    enabled: true,
  },
  websiteEmail: 'hi@litekart.in',
  tax: {
    cgst: 0,
    sgst: 0,
    igst: 0,
  },
  review: {
    enabled: true,
    moderate: false,
  },
  sms: {
    provider: 'fast2sms',
    AUTO_VERIFICATION_ID: 'BoBI72gsKkc',
    enabled: false,
  },
  email: {
    enabled: false,
    from: 'litekart.in <no-reply@litekart.in>',
    cc: ['Swadesh Behera <swadesh@litekart.in>'],
    bcc: ['Customer Service <care@litekart.in>'],
    printers: ['litekart.in <print@hpeprint.com>'],
  },
  payment: {
    PAYPAL_MODE: 'sandbox',
    INSTAMOJO_SANDBOX_MODE: true,
  },
  minimumOrderValue: 0,
  currencyDecimals: 2,
  locationExpiry: 157680000000,
  CDN_URL: '',
  enableStripe: false,
  enableRazorpay: false,
  zips: [],
  userRoles: [
    'user',
    'delivery',
    'support',
    'vendor',
    'manager',
    'admin',
    'super',
  ],
  paymentMethods: ['Stripe', 'Razorpay', 'COD'],
  returnReasons: [
    {
      val: 'DEFECTIVE_PRODUCT',
      name: 'Item or part defective',
    },
    {
      val: 'DAMAGED_PRODUCT',
      name: 'Item or part was broken/damaged on arrival',
    },
    {
      val: 'SIZE_FIT_ISSUES',
      name: 'Size fit issue',
    },
    {
      val: 'QUALITY_ISSUES',
      name: 'Quality issue',
    },
    {
      val: 'MISSHIPMENT',
      name: 'Received a different item',
    },
    {
      val: 'COLOR_STYLE_ISSUES',
      name: 'Color style issue',
    },
    {
      val: 'MISSING_ITEM',
      name: 'Item missing',
    },
    {
      val: 'DEAD_ON_ARRIVAL',
      name: 'Item was dead on arrival',
    },
  ],
}
