export default [
  {
    active: true,
    abandonnedCartRecovery: false,
    annualMonthlyPrice: 0,
    chatSupport: false,
    customDomain: false,
    description: 'Good for starting ecommerce',
    discountCoupons: false,
    emailSupport: true,
    freeSSL: true,
    misReports: false,
    monthlyPrice: 0,
    name: 'FREE',
    onlineStore: true,
    premiumSupport: false,
    productImportExport: false,
    productsAllowed: 10,
    removeMisikiLogo: false,
    salesChannels: false,
    seoOptions: false,
    title: 'Basic ecommerce features',
    transactionFees: 3,
    transactionFeesType: 'percent',
    unlimitedProducts: true,
    unlimitedValidity: true,
  },
  {
    active: true,
    abandonnedCartRecovery: false,
    annualMonthlyPrice: 19,
    chatSupport: true,
    customDomain: true,
    description: 'Best for small business',
    discountCoupons: false,
    emailSupport: true,
    freeSSL: true,
    misReports: false,
    monthlyPrice: 19,
    name: 'Lite',
    onlineStore: true,
    premiumSupport: false,
    productImportExport: false,
    productsAllowed: 100,
    removeMisikiLogo: true,
    salesChannels: false,
    seoOptions: false,
    title: 'All free features + 2% transaction fees',
    transactionFees: 2,
    transactionFeesType: 'percent',
    unlimitedProducts: false,
    unlimitedValidity: false,
  },
  {
    active: true,
    abandonnedCartRecovery: true,
    annualMonthlyPrice: 49,
    chatSupport: true,
    customDomain: true,
    description: 'For medium scale business',
    discountCoupons: true,
    emailSupport: true,
    freeSSL: true,
    misReports: true,
    monthlyPrice: 49,
    name: 'Starter',
    onlineStore: true,
    premiumSupport: false,
    productImportExport: false,
    productsAllowed: 1000,
    removeMisikiLogo: true,
    salesChannels: false,
    seoOptions: false,
    title: 'All Lite features + Discount Coupons',
    transactionFees: 1,
    transactionFeesType: 'percent',
    unlimitedProducts: false,
    unlimitedValidity: false,
  },
  {
    active: true,
    abandonnedCartRecovery: true,
    annualMonthlyPrice: 49,
    chatSupport: true,
    customDomain: true,
    description: 'Best for growing ecommerce',
    discountCoupons: true,
    emailSupport: true,
    freeSSL: true,
    misReports: true,
    monthlyPrice: 49,
    name: 'Pro',
    onlineStore: true,
    premiumSupport: true,
    productImportExport: true,
    productsAllowed: 1000,
    removeMisikiLogo: true,
    salesChannels: true,
    seoOptions: true,
    title: 'Everything in Starter + Unlimited products',
    transactionFees: 1,
    transactionFeesType: 'percent',
    unlimitedProducts: true,
    unlimitedValidity: false,
  },
]
