export default [
  {
    _id: '609233e040fcda1cebaa62f1',
    active: true,
    address: [],
    email: 'user@litekart.in',
    firstName: 'User',
    lastName: 'Litekart',
    password: 'litekart',
    plan: 'free',
    provider: 'local',
    recentlyViewed: [],
    role: 'user',
    roles: ['5eeb952dc4b8c545f46e7e05'],
  },
  {
    _id: '5ed14b669e8b394b6f8967ce',
    active: true,
    email: 'admin@litekart.in',
    firstName: 'Admin',
    lastName: 'Litekart',
    password: 'litekart',
    plan: 'free',
    provider: 'local',
    role: 'admin',
    roles: ['5eeb952dc4b8c545f46e7e02'],
    verified: true,
  },
  {
    _id: '5ec8160b8dec20283f337abb',
    active: true,
    email: 'manager@litekart.in',
    firstName: 'Manager',
    info: {},
    lastName: 'Litekart',
    password: 'litekart',
    provider: 'local',
    role: 'manager',
    roles: ['5eeb952dc4b8c545f46e7e03'],
    verified: true,
  },
  {
    _id: '5ec8160b8dec20283f337aba',
    active: true,
    email: 'super@litekart.in',
    firstName: 'Super',
    info: {},
    lastName: 'Litekart',
    password: 'litekart',
    provider: 'local',
    role: 'super',
    roles: ['5eeb952dc4b8c545f46e7e01'],
    verified: true,
  },
  {
    _id: '5ed14bbe9e8b394b6f8967cf',
    active: true,
    email: 'vendor@litekart.in',
    firstName: 'Vendor',
    info: {},
    lastName: 'Litekart',
    password: 'litekart',
    provider: 'local',
    role: 'vendor',
    roles: ['5eeb952dc4b8c545f46e7e04'],
    verified: true,
  },
]
